# Generated by Django 5.1.4 on 2025-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_coursecontent_coursemember_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Disetujui'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maksimal Siswa'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Rilis'),
        ),
    ]
