# Generated by Django 5.1.4 on 2025-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0009_certificate_delete_coursecompletioncertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handphone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Handphone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
