# Generated by Django 5.1.4 on 2025-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0010_userprofile_description_userprofile_handphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
