# Generated by Django 5.1.4 on 2025-01-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='handphone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
